version: '2.1'
services:
  acorn:
    command: /bin/bash -c 'rm tmp/pids/server.pid; yarn install; bundle install && rake db:create db:migrate && bundle exec rails s -p 3000 -b "0.0.0.0"'
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  db:
    environment:
      MYSQL_ROOT_PASSWORD: acorn1
    env_file:
      - ./.env
    image: mysql:5.7.9
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql